export * from './Form.forgotPassword';
export * from './Form.forgotPasswordSent';
export * from './Form.instituteReview';
export * from './Form.login';
export * from './Form.register';
export * from './Form.resetPassword';
export * from './Form.verifyEmail';
export * from './Form.verifyEmailRequest';
export * from './Form.verifyEmailSent';
