import {
  IconBookmark,
  IconBriefcase,
  IconBuilding,
  IconBuildingCommunity,
  IconChalkboard,
  IconChartBar,
  IconChevronDown,
  IconChevronRight,
  IconCircleXFilled,
  IconDots,
  IconFileText,
  IconFilter,
  IconGps,
  IconHeartHandshake,
  IconHelp,
  IconHelpCircle,
  IconHistory,
  IconHourglass,
  IconLink,
  IconLoader2,
  IconMail,
  IconMap,
  IconMapPin,
  IconMenu,
  IconMessage,
  IconMoodSmile,
  IconNotes,
  IconPencil,
  IconPencilPlus,
  IconPhone,
  IconSalad,
  IconSchool,
  IconSearch,
  IconSettings,
  IconShare,
  IconShieldCheck,
  IconShieldLock,
  IconStar,
  IconStarFilled,
  IconTarget,
  IconTrophy,
  IconUser,
  IconUserScan,
  IconUsersGroup,
  IconWifi,
  IconZoom,
} from '@tabler/icons-react';

export const AppIcons = {
  school: IconSchool,
  chalkboard: IconChalkboard,
  chartBar: IconChartBar,
  filter: IconFilter,
  star: IconStar,
  building: IconBuilding,
  history: IconHistory,
  pencilPlus: IconPencilPlus,
  notes: IconNotes,
  hourglass: IconHourglass,
  zoom: IconZoom,
  menu: IconMenu,
  chevronDown: IconChevronDown,
  chevronRight: IconChevronRight,
  search: IconSearch,
  teacher: IconUser,
  institute: IconBuilding,
  circleXFilled: IconCircleXFilled,
  map: IconMap,
  user: IconUser,
  trophy: IconTrophy,
  message: IconMessage,
  help: IconHelp,
  settings: IconSettings,
  target: IconTarget,
  mail: IconMail,
  fileText: IconFileText,
  shieldLock: IconShieldLock,
  helpCircle: IconHelpCircle,
  pencil: IconPencil,
  loader: IconLoader2,
  userScan: IconUserScan,
  starFilled: IconStarFilled,
  bookmark: IconBookmark,
  share: IconShare,
  briefcase: IconBriefcase,
  buildingCommunity: IconBuildingCommunity,
  heartHandshake: IconHeartHandshake,
  mapPin: IconMapPin,
  moodSmile: IconMoodSmile,
  salad: IconSalad,
  shieldCheck: IconShieldCheck,
  usersGroup: IconUsersGroup,
  wifi: IconWifi,
  gps: IconGps,
  link: IconLink,
  phone: IconPhone,
  dots: IconDots,
};
